name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.

  - type: dropdown
    id: package
    attributes:
      label: Which package is affected?
      multiple: true
      options:
        - gameframework (core)
        - gameframework_unity
        - gameframework_unreal
        - Example app
        - Documentation
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Tell us what went wrong
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Initialize engine with '...'
        2. Call method '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: Please provide a minimal code sample that reproduces the issue
      render: dart
      placeholder: |
        import 'package:gameframework/gameframework.dart';
        
        void main() {
          // Your code here
        }

  - type: textarea
    id: logs
    attributes:
      label: Logs / Error Messages
      description: Please paste any relevant logs or error messages
      render: shell

  - type: dropdown
    id: platforms
    attributes:
      label: Platform(s) Affected
      multiple: true
      options:
        - Android
        - iOS
        - macOS
        - Windows
        - Linux
        - Web
    validations:
      required: true

  - type: input
    id: flutter-version
    attributes:
      label: Flutter Version
      description: Output of `flutter --version`
      placeholder: "Flutter 3.27.0"
    validations:
      required: true

  - type: input
    id: package-version
    attributes:
      label: Package Version
      description: Version of gameframework package you're using
      placeholder: "0.0.1"
    validations:
      required: true

  - type: dropdown
    id: engine
    attributes:
      label: Game Engine (if applicable)
      options:
        - Unity
        - Unreal Engine
        - N/A
    validations:
      required: true

  - type: input
    id: engine-version
    attributes:
      label: Engine Version (if applicable)
      placeholder: "Unity 2022.3.20f1 or Unreal 5.3.2"

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched for existing issues
          required: true
        - label: I have provided a minimal code sample
          required: true
        - label: I have included relevant logs/error messages
          required: true
        - label: I am using the latest version of the package
          required: false
