name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below.

  - type: dropdown
    id: package
    attributes:
      label: Which package should this feature be added to?
      multiple: true
      options:
        - gameframework (core)
        - gameframework_unity
        - gameframework_unreal
        - Example app
        - Documentation
        - New package
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it address?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: I would like to have...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: I've tried...

  - type: textarea
    id: api-design
    attributes:
      label: API Design (if applicable)
      description: If you have ideas about the API, share them here
      render: dart
      placeholder: |
        // Example usage
        final controller = await UnityController.create(
          newFeature: true,
          featureOptions: FeatureOptions(...),
        );

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Blocking my use case
        - Critical - Cannot use package without this
    validations:
      required: true

  - type: dropdown
    id: platforms
    attributes:
      label: Target Platform(s)
      multiple: true
      options:
        - Android
        - iOS
        - macOS
        - Windows
        - Linux
        - Web
        - All platforms
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your use case in detail
      placeholder: I'm building an AR app that needs...
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or references here

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I am willing to submit a PR for this feature
          required: false
        - label: I am willing to help test this feature
          required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched for existing feature requests
          required: true
        - label: This feature aligns with the project's goals
          required: true
        - label: I have clearly described the problem and solution
          required: true
