import 'dart:io';
import 'package:path/path.dart' as path;
import 'package:yaml/yaml.dart';
import '../../models/game_config.dart';

/// Loads and parses .game.yml configuration
class ConfigLoader {
  static const String configFileName = '.game.yml';

  /// Find .game.yml file in current or parent directories
  static File? findConfigFile({String? startPath}) {
    var dir = Directory(startPath ?? Directory.current.path);

    // Search up to 5 levels
    for (var i = 0; i < 5; i++) {
      final configFile = File(path.join(dir.path, configFileName));
      if (configFile.existsSync()) {
        return configFile;
      }

      final parent = dir.parent;
      if (parent.path == dir.path) break; // Reached root
      dir = parent;
    }

    return null;
  }

  /// Load configuration from file
  static GameConfig loadConfig({String? configPath}) {
    File? configFile;

    if (configPath != null) {
      configFile = File(configPath);
      if (!configFile.existsSync()) {
        throw Exception('Config file not found: $configPath');
      }
    } else {
      configFile = findConfigFile();
      if (configFile == null) {
        throw Exception(
          'No $configFileName found. Run "game init" to create one.',
        );
      }
    }

    final content = configFile.readAsStringSync();
    final yaml = loadYaml(content) as YamlMap;

    return GameConfig.fromYaml(yaml);
  }

  /// Create a default .game.yml template
  static String createDefaultConfig({
    required String projectName,
    bool includeUnity = true,
    bool includeUnreal = false,
  }) {
    final buffer = StringBuffer();

    buffer.writeln('# Flutter Game Framework Configuration');
    buffer.writeln('# Generated by game CLI');
    buffer.writeln();
    buffer.writeln('name: $projectName');
    buffer.writeln('version: 1.0.0');
    buffer.writeln();
    buffer.writeln('# Engine configurations');
    buffer.writeln('engines:');

    if (includeUnity) {
      buffer.writeln('  unity:');
      buffer.writeln('    # Path to your Unity project');
      buffer.writeln('    project_path: ../YourUnityProject');
      buffer.writeln();
      buffer.writeln('    # Where Unity exports are saved');
      buffer.writeln('    export_path: ../YourUnityProject/Exports');
      buffer.writeln();
      buffer.writeln('    # Export settings');
      buffer.writeln('    export_settings:');
      buffer.writeln('      development: false');
      buffer.writeln('      build_configuration: Release');
      buffer.writeln('      scenes:');
      buffer.writeln('        - MainMenu');
      buffer.writeln('        - Gameplay');
      buffer.writeln();
      buffer.writeln('    # Platform configurations');
      buffer.writeln('    platforms:');
      buffer.writeln('      android:');
      buffer.writeln('        enabled: true');
      buffer.writeln('        target_path: android/unityLibrary');
      buffer.writeln('        build_settings:');
      buffer.writeln('          export_project: true');
      buffer.writeln('          scripting_backend: IL2CPP');
      buffer.writeln('          target_architectures: [ARM64]');
      buffer.writeln();
      buffer.writeln('      ios:');
      buffer.writeln('        enabled: true');
      buffer.writeln('        target_path: ios/UnityFramework.framework');
      buffer.writeln('        build_settings:');
      buffer.writeln('          symlink_libraries: true');
      buffer.writeln();
      buffer.writeln('      macos:');
      buffer.writeln('        enabled: false');
      buffer.writeln('        target_path: macos/UnityFramework.framework');
      buffer.writeln();
      buffer.writeln('      windows:');
      buffer.writeln('        enabled: false');
      buffer.writeln('        target_path: windows/unity_build');
      buffer.writeln();
      buffer.writeln('      linux:');
      buffer.writeln('        enabled: false');
      buffer.writeln('        target_path: linux/unity_build');
      buffer.writeln();
    }

    if (includeUnreal) {
      buffer.writeln('  unreal:');
      buffer.writeln('    # Path to your Unreal project');
      buffer.writeln('    project_path: ../YourUnrealProject');
      buffer.writeln();
      buffer.writeln('    # Where Unreal packages are saved');
      buffer.writeln('    export_path: ../YourUnrealProject/Packaged');
      buffer.writeln();
      buffer.writeln('    # Export settings');
      buffer.writeln('    export_settings:');
      buffer.writeln('      development: false');
      buffer.writeln('      build_configuration: Shipping');
      buffer.writeln('      levels:');
      buffer.writeln('        - MainMenu');
      buffer.writeln('        - Level_01');
      buffer.writeln();
      buffer.writeln('    # Platform configurations');
      buffer.writeln('    platforms:');
      buffer.writeln('      android:');
      buffer.writeln('        enabled: true');
      buffer.writeln('        target_path: android/app/src/main');
      buffer.writeln('        build_settings:');
      buffer.writeln('          architecture: ARM64');
      buffer.writeln('          package_data_in_apk: false');
      buffer.writeln();
      buffer.writeln('      ios:');
      buffer.writeln('        enabled: true');
      buffer.writeln('        target_path: ios/UnrealFramework.framework');
      buffer.writeln('        build_settings:');
      buffer.writeln('          minimum_ios_version: 12.0');
      buffer.writeln();
      buffer.writeln('      macos:');
      buffer.writeln('        enabled: false');
      buffer.writeln('        target_path: macos/UnrealFramework.framework');
      buffer.writeln();
      buffer.writeln('      windows:');
      buffer.writeln('        enabled: false');
      buffer.writeln('        target_path: windows/unreal_build');
      buffer.writeln();
      buffer.writeln('      linux:');
      buffer.writeln('        enabled: false');
      buffer.writeln('        target_path: linux/unreal_build');
    }

    return buffer.toString();
  }

  /// Validate configuration
  static List<String> validateConfig(GameConfig config) {
    final errors = <String>[];

    if (config.name.isEmpty) {
      errors.add('Project name is required');
    }

    if (config.engines.isEmpty) {
      errors.add('At least one engine must be configured');
    }

    for (final entry in config.engines.entries) {
      final engineType = entry.key;
      final engineConfig = entry.value;

      if (engineConfig.projectPath.isEmpty) {
        errors.add('$engineType: project_path is required');
      }

      if (engineConfig.platforms.isEmpty) {
        errors.add('$engineType: at least one platform must be configured');
      }

      // Check if project path exists
      final projectDir = Directory(engineConfig.projectPath);
      if (!projectDir.existsSync()) {
        errors.add(
          '$engineType: project_path does not exist: ${engineConfig.projectPath}',
        );
      }
    }

    return errors;
  }
}
